### ISSUE TITLE
Including slf4j jars in class path

### ISSUE THREAD

**Issue by swistaczek** [projectodd/wunderboss#11]
Hello,
In my project I use JBundler to resolve jar deps, currently I use kafka jars from maven:
```ruby
jar 'org.apache.kafka:kafka_2.9.2', '0.8.1' #, exclusions: ['com.sun.jdmk:jmxtools', 'javax.jms:jms', 'com.sun.jmx:jmxri']
jar 'log4j:log4j', '1.2.14' # Including this brings in correct jmx deps for kafka. Weird.
jar 'jline:jline', '2.11'
```

I try to use ```torquebox-web``` as my primary web server but then I get following errors:
```ruby
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/ernest.bursa/.m2/repository/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/ernest.bursa/.rvm/gems/jruby-1.7.16@meta-offer/gems/torquebox-core-4.x.incremental.255-java/lib/wunderboss-jars/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

Is it possible to move wunderboss JAR deps to be managed via JBundler?

**Comment by tobias** [comment]
This is probably a TorqueBox issue, since wunderboss deps are just standard maven deps. The solution may be to build TorqueBox with JBunder, but that would probably require users to use JBundler fo build their own apps as well, which isn't ideal. /cc @bbrowning

**Comment by tobias** [comment]
Ah, I see you already created a TorqueBox issue for it: https://github.com/torquebox/torquebox/issues/200
