### ISSUE TITLE
Wunderboss failed to load class "MessagingService" from package "org.jboss.as.messaging" 

### ISSUE THREAD

**Issue by shivgana** [projectodd/wunderboss#24]
Hi @tobias,

Immutant/messaging served as a dependence in our project, and Wildfly is unable to deploy it. Due to a condition in wunderboss/wildfly-core that attempts to load the MessagingService class from either the "org.jboss.as.messaging" or the "org.wildfly.extension.messaging.activemq" package, depending on the wildfly version.

Condition file: [In AsUtils.java of wildlfy-core, line 172 & 177](https://github.com/projectodd/wunderboss/blob/master/wildfly/core/src/main/java/org/projectodd/wunderboss/as/ASUtils.java) 

I checked the tar files for the three unique versions "21.0.0," "24.0.1," and most recent "28.0.0" at wildfly. By default, Wildfly offers the org.jboss.as.messaging package, but it does not contain the Class MessagingService.
![image](https://github.com/projectodd/wunderboss/assets/51191342/a15bf054-7303-4d07-abca-ad5936159aba)

We have found another maven package for jboss Messaging i.e [module "org.jboss.as" name "jboss-as-messaging" Maven repository](https://mvnrepository.com/artifact/org.jboss.as/jboss-as-messaging)

Module jboss-as-messaging contains class MessagingService.
![image](https://github.com/projectodd/wunderboss/assets/51191342/6a639e72-a200-4ec5-b800-db8dee2421f8)

Question:

1.  If there is not class in org.jboss.as.messaging, why it is mentioned in code to load class from it.

Request:

1.  Can you revisit the code and update it.

CC: @jcrossley3 , @headius , @bobmcwhirter

**Comment by tobias** [comment]
Hi @shivgana! Thanks for the thorough report.

The reason this is happening is Wunderboss was never updated to support any versions of Wildfly greater than Wildfly 10. This is a dead project unfortunately, so won't receive any new updates to address this.
